[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pool_party = "3inmw7qcywQirQoNSL54MhqoG7CJ58ZYwVCYSmC1TTB4"
# raydium_clmm = "devi51mZmdwUJGU9hjN27vEz64Gps7uUefqxg27EAtH"

# [programs.devnet]
# raydium_clmm = "devi51mZmdwUJGU9hjN27vEz64Gps7uUefqxg27EAtH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
